/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Mokleters
 */
public class Frame1 extends javax.swing.JFrame {
         String temp = "";
         Double h1,ti,bt = null;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Ideal = new javax.swing.JTextField();
        Saran = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Lakilaki = new javax.swing.JRadioButton();
        Perempuan = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();
        btnCoba = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Berat = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cek Ideal Tubuh");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel3.setText("Berat Badan Anda Adalah");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 30));

        jLabel4.setText("kg");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 80, 30));

        jLabel5.setText("Tinggi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 20));

        jLabel6.setText("Berat Badan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 20));

        jLabel7.setText("Jenis Kelamin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 20));

        Ideal.setEditable(false);
        getContentPane().add(Ideal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 70, 30));

        Saran.setEditable(false);
        getContentPane().add(Saran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 400, 30));
        getContentPane().add(Tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, 30));

        buttonGroup1.add(Lakilaki);
        Lakilaki.setText("Laki-laki");
        getContentPane().add(Lakilaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        buttonGroup1.add(Perempuan);
        Perempuan.setText("Perempuan");
        getContentPane().add(Perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btnCoba.setText("Coba Lagi");
        btnCoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCoba, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel8.setText("Nama");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, 20));

        jLabel9.setText("cm");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, 30));

        jLabel2.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel10.setText("kg");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 80, 30));
        getContentPane().add(Berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 70, 30));
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, 30));

        Hasil.setEditable(false);
        getContentPane().add(Hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 400, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        
        if (Nama.getText().equals("")
                ||Tinggi.getText().equals("")
                |Berat.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Data harus diisikan semua");
        } else if(Perempuan.isSelected()
                ||Lakilaki.isSelected()){
            try {
            Proses();
            } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Inputan Ada Yang Belum Diisi");
        }
        } else {
                JOptionPane.showMessageDialog(null, "Radio Button Harus Dipilih");
                }
        
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobaActionPerformed
        Nama.setText("");
        Tinggi.setText("");
        Berat.setText("");
        Ideal.setText("");
        Hasil.setText("");
        Saran.setText("");
        buttonGroup1.clearSelection(); 
        Lakilaki.setSelected(false);
        Perempuan.setSelected(false);
    }//GEN-LAST:event_btnCobaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
    dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField Ideal;
    private javax.swing.JRadioButton Lakilaki;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.JTextField Saran;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton btnCoba;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(Tinggi.getText());
        bt = Double.parseDouble(Berat.getText());
        
        
        
        if(Perempuan.isSelected()){
            h1 = (ti - 100) * 1;
        } else if (Lakilaki.isSelected()){
            h1 = (ti - 104) * 1;
        } temp = Double.toString(h1.intValue());
        
        if (h1 < bt) {
            Ideal.setText(temp);
            Hasil.setText("Maaf " + Nama.getText() + ", Sepertinya Anda Overweight");
            Saran.setText("Banyaklah Berolahraga dan Hindari Makanan Berkolesterol");
        } else if (h1 > bt) {
            Ideal.setText(temp);
            Hasil.setText("Maaf " + Nama.getText() + ", Sepertinya Anda Underweight");
            Saran.setText("Banyaklah Mengonsumsi Makanan Berkarbohidrat");
        } else{
            Ideal.setText(temp);
            Hasil.setText("Halo " + Nama.getText() + ", Berat Badan Anda Sudah Ideal");
            Saran.setText("Lanjutkan Pola Makan Teratur dan Gaya Hidup Sehat");
        }
    }
}
